### ISSUE TITLE
Add gitflow check to have at least 2 approves and clean test pass for merge

### ISSUE THREAD

**Issue by rareddy** [bf2fc6cc711aee1a0c2a/kas-fleetshard#590]
In order to comply with some security requirements, we need to have these enforcements implemented.

**Comment by MikeEdgar** [comment]
I've added these branch protections for `main`:
![image](https://user-images.githubusercontent.com/20868526/155733940-d5aac9ae-93bc-4ee8-883e-d667a16655a5.png)

**Comment by shawkins** [comment]
This is new: https://github.com/bf2fc6cc711aee1a0c2a/kas-fleetshard/runs/5335310133?check_suite_focus=true#step:2:6

**Comment by MikeEdgar** [comment]
Yes - it seems to be related to forks of a public repo not having permission to add labels. There seems to be solutions [1], but maybe not a simple/one-line change.

[1] https://github.com/actions/labeler/issues/12#issuecomment-1019246202

**Comment by MikeEdgar** [comment]
I updated the branch protection to only require that `build` passes before merging to `main`.

**Comment by shawkins** [comment]
Seems to be working as intended, closing.
