### ISSUE TITLE
osd-provision script terminates shell on error

### ISSUE THREAD

**Issue by shawkins** [bf2fc6cc711aee1a0c2a/kas-fleetshard#660]
If you run perf/scripts/osd-provision.sh and something goes wrong, your whole terminal session will go away.  The workaround is to call the script as a background process.

**Comment by kornys** [comment]
well this is weird, because I have never seen this behavior also in pipeline it works fine.

**Comment by shawkins** [comment]
Just now looking at this again.  It's the update_env.sh that's the culprit - I had taken that from an earlier script in the gitlab repo and didn't look at it closely enough.
